### ISSUE TITLE
Blog posts disagree on the year

### ISSUE THREAD

**Issue by erooke** [uiowa-mgb/website#12]
While mucking about with the blog I noticed that the two blog posts about qual prep materials: https://github.com/uiowa-mgb/website/blob/master/content/Blog/quals/analysis_jstarr.md and https://github.com/uiowa-mgb/website/blob/master/content/Blog/quals/analysis_adriana.md both have the date listed as 2022 and 2023 within themselves. I'm not sure if this is something worth fixing but thought I would point it out.

**Comment by Joecstarr** [comment]
Totally worth fixing

**Comment by Joecstarr** [comment]
Actually I don't see anything wrong. Materials are from last summer prep. Posted in summer 2023.

**Comment by erooke** [comment]
For sure, I was just confused by them begin tagged 2022 but that makes sense.
